name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call deploy webhook
        run: |
          curl -X POST \
            -H "X-DEPLOY-TOKEN: ${{ secrets.DEPLOY_TOKEN }}" \
            https://guillaumedbx.pythonanywhere.com/deploy
